# Default values for my-flask-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1


image:
  repository: bitandocker/flask-app
  tag: 0.0.3

service:
  type: NodePort
  port: 5000
  targetPort: 8282
  nodePort: 30007

